export interface BuiltinMaterial {
  id: string;
  name: string;
  category: 'flower' | 'greenery' | 'line' | 'vase';
  kind: string;
  colors: string[];
  shape?: string;
  previewUrl?: string;
  minAppVersion?: string;
}

export const MATERIAL_CATEGORIES = [
  { id: 'flower', label: '花朵' },
  { id: 'greenery', label: '枝叶' },
  { id: 'line', label: '线条' },
  { id: 'vase', label: '花器' },
];

/** 内置素材元数据。本文件由 scripts/import-real-materials-v2.mjs 生成，勿手工编辑；
 *  真花照片素材（透明底 PNG 存 OSS），kind/colors 为矢量时代遗留字段，接口不下发。 */
export const BUILTIN_MATERIALS: BuiltinMaterial[] = [
  {
    id: 'mat-lily',
    name: '百合花',
    category: 'flower',
    kind: 'lily',
    colors: [],
  },
  {
    id: 'mat-cymbidium',
    name: '大花蕙兰',
    category: 'flower',
    kind: 'cymbidium',
    colors: [],
  },
  {
    id: 'mat-dahlia',
    name: '大丽花',
    category: 'flower',
    kind: 'dahlia',
    colors: [],
  },
  {
    id: 'mat-gerbera',
    name: '非洲菊',
    category: 'flower',
    kind: 'gerbera',
    colors: [],
  },
  {
    id: 'mat-cosmos',
    name: '格桑花',
    category: 'flower',
    kind: 'cosmos',
    colors: [],
  },
  {
    id: 'mat-chrysanthemum',
    name: '菊花',
    category: 'flower',
    kind: 'chrysanthemum',
    colors: [],
  },
  {
    id: 'mat-carnation',
    name: '康乃馨',
    category: 'flower',
    kind: 'carnation',
    colors: [],
  },
  {
    id: 'mat-lotus',
    name: '莲花',
    category: 'flower',
    kind: 'lotus',
    colors: [],
  },
  {
    id: 'mat-calla',
    name: '马蹄莲',
    category: 'flower',
    kind: 'calla',
    colors: [],
  },
  {
    id: 'mat-rose',
    name: '玫瑰',
    category: 'flower',
    kind: 'rose',
    colors: [],
  },
  {
    id: 'mat-peony',
    name: '牡丹',
    category: 'flower',
    kind: 'peony',
    colors: [],
  },
  {
    id: 'mat-hibiscus',
    name: '木槿花',
    category: 'flower',
    kind: 'hibiscus',
    colors: [],
  },
  {
    id: 'mat-camellia',
    name: '山茶花',
    category: 'flower',
    kind: 'camellia',
    colors: [],
  },
  {
    id: 'mat-geranium',
    name: '天竺葵',
    category: 'flower',
    kind: 'geranium',
    colors: [],
  },
  {
    id: 'mat-sunflower',
    name: '向日葵',
    category: 'flower',
    kind: 'sunflower',
    colors: [],
  },
  {
    id: 'mat-eustoma',
    name: '洋桔梗',
    category: 'flower',
    kind: 'eustoma',
    colors: [],
  },
  {
    id: 'mat-magnolia',
    name: '玉兰花',
    category: 'flower',
    kind: 'magnolia',
    colors: [],
  },
  {
    id: 'mat-tulip',
    name: '郁金香',
    category: 'flower',
    kind: 'tulip',
    colors: [],
  },
  {
    id: 'mat-gardenia',
    name: '栀子花',
    category: 'flower',
    kind: 'gardenia',
    colors: [],
  },
  {
    id: 'mat-limonium',
    name: '补血草',
    category: 'flower',
    kind: 'limonium',
    colors: [],
  },
  {
    id: 'mat-lilac',
    name: '丁香',
    category: 'flower',
    kind: 'lilac',
    colors: [],
  },
  {
    id: 'mat-ilex-berry',
    name: '冬青果',
    category: 'flower',
    kind: 'ilex-berry',
    colors: [],
  },
  {
    id: 'mat-delphinium',
    name: '飞燕草',
    category: 'flower',
    kind: 'delphinium',
    colors: [],
  },
  {
    id: 'mat-hyacinth',
    name: '风信子',
    category: 'flower',
    kind: 'hyacinth',
    colors: [],
  },
  {
    id: 'mat-cottonrose',
    name: '芙蓉花',
    category: 'flower',
    kind: 'cottonrose',
    colors: [],
  },
  {
    id: 'mat-crabapple',
    name: '海棠',
    category: 'flower',
    kind: 'crabapple',
    colors: [],
  },
  {
    id: 'mat-plumeria',
    name: '鸡蛋花',
    category: 'flower',
    kind: 'plumeria',
    colors: [],
  },
  {
    id: 'mat-bluestarflower',
    name: '蓝星花',
    category: 'flower',
    kind: 'bluestarflower',
    colors: [],
  },
  {
    id: 'mat-lily-of-the-valley',
    name: '铃兰',
    category: 'flower',
    kind: 'lily-of-the-valley',
    colors: [],
  },
  {
    id: 'mat-astilbe',
    name: '落新妇',
    category: 'flower',
    kind: 'astilbe',
    colors: [],
  },
  {
    id: 'mat-gypsophila',
    name: '满天星',
    category: 'flower',
    kind: 'gypsophila',
    colors: [],
  },
  {
    id: 'mat-spider-lily',
    name: '石蒜',
    category: 'flower',
    kind: 'spider-lily',
    colors: [],
  },
  {
    id: 'mat-narcissus',
    name: '水仙花',
    category: 'flower',
    kind: 'narcissus',
    colors: [],
  },
  {
    id: 'mat-gladiolus',
    name: '唐菖蒲',
    category: 'flower',
    kind: 'gladiolus',
    colors: [],
  },
  {
    id: 'mat-cowherb',
    name: '王不留行',
    category: 'flower',
    kind: 'cowherb',
    colors: [],
  },
  {
    id: 'mat-hydrangea',
    name: '绣球',
    category: 'flower',
    kind: 'hydrangea',
    colors: [],
  },
  {
    id: 'mat-spiraea',
    name: '绣线菊',
    category: 'flower',
    kind: 'spiraea',
    colors: [],
  },
  {
    id: 'mat-sweet-william',
    name: '须苞石竹',
    category: 'flower',
    kind: 'sweet-william',
    colors: [],
  },
  {
    id: 'mat-anemone',
    name: '银莲花',
    category: 'flower',
    kind: 'anemone',
    colors: [],
  },
  {
    id: 'mat-catchfly',
    name: '蝇子草',
    category: 'flower',
    kind: 'catchfly',
    colors: [],
  },
  {
    id: 'mat-iris',
    name: '鸢尾',
    category: 'flower',
    kind: 'iris',
    colors: [],
  },
  {
    id: 'mat-stock',
    name: '紫罗兰',
    category: 'flower',
    kind: 'stock',
    colors: [],
  },
  {
    id: 'mat-melaleuca',
    name: '白千层',
    category: 'greenery',
    kind: 'melaleuca',
    colors: [],
  },
  {
    id: 'mat-ivy',
    name: '常春藤',
    category: 'greenery',
    kind: 'ivy',
    colors: [],
  },
  {
    id: 'mat-maple',
    name: '枫叶',
    category: 'greenery',
    kind: 'maple',
    colors: [],
  },
  {
    id: 'mat-olive',
    name: '橄榄叶',
    category: 'greenery',
    kind: 'olive',
    colors: [],
  },
  {
    id: 'mat-davallia-mariesii',
    name: '高山羊齿',
    category: 'greenery',
    kind: 'davallia-mariesii',
    colors: [],
  },
  {
    id: 'mat-monstera',
    name: '龟背竹',
    category: 'greenery',
    kind: 'monstera',
    colors: [],
  },
  {
    id: 'mat-pittosporum',
    name: '海桐',
    category: 'greenery',
    kind: 'pittosporum',
    colors: [],
  },
  {
    id: 'mat-alocasia',
    name: '海芋',
    category: 'greenery',
    kind: 'alocasia',
    colors: [],
  },
  {
    id: 'mat-ruscus',
    name: '假叶树',
    category: 'greenery',
    kind: 'ruscus',
    colors: [],
  },
  {
    id: 'mat-yucca',
    name: '丝兰',
    category: 'greenery',
    kind: 'yucca',
    colors: [],
  },
  {
    id: 'mat-davallia',
    name: '兔脚蕨',
    category: 'greenery',
    kind: 'davallia',
    colors: [],
  },
  {
    id: 'mat-eucalyptus',
    name: '尤加利',
    category: 'greenery',
    kind: 'eucalyptus',
    colors: [],
  },
  {
    id: 'mat-white-plum',
    name: '白梅',
    category: 'line',
    kind: 'white-plum',
    colors: [],
  },
  {
    id: 'mat-amaranthus',
    name: '狐尾苋',
    category: 'line',
    kind: 'amaranthus',
    colors: [],
  },
  {
    id: 'mat-forsythia',
    name: '连翘',
    category: 'line',
    kind: 'forsythia',
    colors: [],
  },
  {
    id: 'mat-willow',
    name: '柳',
    category: 'line',
    kind: 'willow',
    colors: [],
  },
  {
    id: 'mat-pieris',
    name: '马醉木',
    category: 'line',
    kind: 'pieris',
    colors: [],
  },
  {
    id: 'mat-allium',
    name: '弯葱',
    category: 'line',
    kind: 'allium',
    colors: [],
  },
  {
    id: 'mat-snowwillow',
    name: '雪柳',
    category: 'line',
    kind: 'snowwillow',
    colors: [],
  },
  {
    id: 'mat-bamboo',
    name: '竹',
    category: 'line',
    kind: 'bamboo',
    colors: [],
  },
  {
    id: 'mat-vase-round-ceramic-white',
    name: '白瓷圆瓶',
    category: 'vase',
    kind: 'vase-round-ceramic-white',
    colors: [],
  },
  {
    id: 'mat-vase-ruffle-ceramic-white',
    name: '白瓷褶边瓶',
    category: 'vase',
    kind: 'vase-ruffle-ceramic-white',
    colors: [],
  },
  {
    id: 'mat-vase-ruffle-glass-pink',
    name: '粉色褶边玻璃瓶',
    category: 'vase',
    kind: 'vase-ruffle-glass-pink',
    colors: [],
  },
  {
    id: 'mat-vase-small-round-ceramic-black',
    name: '黑瓷小圆瓶',
    category: 'vase',
    kind: 'vase-small-round-ceramic-black',
    colors: [],
  },
  {
    id: 'mat-vase-pitcher-stoneware-black',
    name: '黑色石陶水壶瓶',
    category: 'vase',
    kind: 'vase-pitcher-stoneware-black',
    colors: [],
  },
  {
    id: 'mat-vase-tall-recycled-glass-green',
    name: '绿色高玻璃瓶',
    category: 'vase',
    kind: 'vase-tall-recycled-glass-green',
    colors: [],
  },
  {
    id: 'mat-vase-large-stoneware-warm-brown',
    name: '暖棕大号石陶瓶',
    category: 'vase',
    kind: 'vase-large-stoneware-warm-brown',
    colors: [],
  },
  {
    id: 'mat-vase-terracotta-medium-ceramic-tan',
    name: '陶土色中陶罐',
    category: 'vase',
    kind: 'vase-terracotta-medium-ceramic-tan',
    colors: [],
  },
];
